Update upload_ccache

diff --git a/upload_ccache b/upload_ccache
--- a/upload_ccache
+++ b/upload_ccache
@@ -1,37 +1,34 @@
 #!/bin/bash
 
-cd /tmp
+# Change to the Source Directory
+cd /tmp/rom
 
-up () {
-  if [ -e $1 ]; then
-  echo "uploading $1"
-	curl --retry 18 --upload-file $1 bashupload.com
-	# 3d, 50g limit
-  fi
-}
+# Display a message
+echo "============================"
+echo "Uploading the Build..."
+echo "============================"
 
-# Compress function with pigz for faster compression
-com ()
-{
-    tar --use-compress-program="pigz -k -$2 " -cf $1.tar.gz $1
-}
+# Change to the Output Directory
+cd out/target/product/mido
 
-echo "|| Compressing CCACHE ||"
+# List the Files
+echo "Files inside /tmp/rom/out/target/product/mido are:"
+ls --color=auto
 
-# First compress in with pogz in a single zip.
-time com ccache 1 # Compression level 1, its enough
+# Set FILENAME var
+FILENAME=$(echo syberia*.zip)
 
-# Now split in 0.4GB parts
-#7za a -tzip -v400m -mx=0 ccache_backup.zip ccache.tar.gz
+# Upload to oshi.at
+if [ -z "$TIMEOUT" ];then
+    TIMEOUT=20160
+fi
 
-# upload all parts
-echo "|| Uploading CCACHE ||"
-for i in /tmp/ccache_backup.zip; do
-   time up ${i}
-done
+curl -T $FILENAME https://oshi.at/${FILENAME}/${TIMEOUT} | tee link.txt > /dev/null || { echo "ERROR: Failed to Upload the Build!" && exit 1; }
 
-sleep 5
-echo "|| Uploaded ||"
+# Show the Download Link
+echo "=============================================="
+cat link.txt || { echo "ERROR: Failed to Upload the Build!" && exit 1; }
+echo "=============================================="
 
-# clean storage
-rm -rf /tmp/rom
+# Exit
+exit 0
